language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  
script:
  - xvfb-run npm run pwa

after_success:
  - firebase deploy - project dough-4f780 - token $FIREBASE_TOKEN.